version: '3.8'
services:
  # fe-app:
  #   image: registry.cn-zhangjiakou.aliyuncs.com/esmio/simon:aaa
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - nest-app
  #   networks:
  #     - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    restart: always
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/concerto/mysql-data:/var/lib/mysql
    # command: echo '111'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置默认字符集
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/concerto/redis-data:/data
    restart: always
    networks:
      - common-network
  minio-container:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /Users/concerto/minio-data:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: simon
      MINIO_ROOT_PASSWORD: 11112222
    restart: always
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
